# Generated by Django 5.1.5 on 2025-02-08 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='job',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MaxLengthValidator(128)]),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='full_name',
            field=models.CharField(default=None, max_length=128, validators=[django.core.validators.MaxLengthValidator(128)]),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
