# Generated by Django 5.1.4 on 2025-01-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(default='adress', max_length=255),
            preserve_default=False,
        ),
    ]
