# Generated by Django 5.1.5 on 2025-02-08 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='full_name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MaxLengthValidator(128), django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.MaxLengthValidator(13), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
