# Generated by Django 5.1.5 on 2025-01-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
