# Generated by Django 5.1.5 on 2025-01-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmodel_discount_and_more'),
        ('products', '0002_alter_productmodel_options'),
    ]

    operations = [
    ]
