# Generated by Django 5.1.5 on 2025-01-30 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20250130_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='quantity'),
        ),
    ]
